languageCode = "en-us"
title = "ZLSA Design"
baseurl = "http://zlsadesign.com/"
theme = "zlsadesign"
pluralizelisttitles = true
paginate = 10
preserveTaxonomyNames = true
canonifyURLs = true

PygmentsUseClasses = true
PygmentsCodeFences = true

[Params]
description = "I make spaceflight infographics, software, and a lot of other things. I also like spaceships."
author = "Jon Ross"
keywords = ["infographic", "art", "javascript", "programming"]
